### ISSUE TITLE
[Bug] 1.18.4 /firecrawl-js NPM package missing dist directory

### ISSUE THREAD

**Issue by kcharvi** [kcharvi/firecrawl-with-ai-agents#104]
**Describe the Bug**
Version 1.18.4 of /firecrawl-js published to NPM is missing the dist directory, resulting in errors like this:
```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'node_modules//firecrawl-js/dist/index.js'
```
```
$ ls -1 node_modules//firecrawl-js
node_modules/
src/
.env.example
jest.config.js
LICENSE
package.json
README.md
tsconfig.json
tsup.config.ts
```

---
*Originally from mendableai/firecrawl #1272 by @b0o on 2025-02-27T22:38:37+00:00*

**Comment by kcharvi** [comment]
**nickscamara commented on 2025-02-27T23:40:37+00:00 (Original)**:

Hey   sorry about that, we just pushed a patch fix. Should be working in 1.18.5 now!
